name: Build on create a release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build tagged version
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: Atlas-Authority/atlassian-marketplace-release-action/release@main
        with:
          branch: main
          githubUserName: DevOps
          githubUserEmail: devops@atlasauthority.com
          githubToken: ${{ secrets.GHA_ADMIN }}
          marketplaceUser: devops@atlasauthority.com
          marketplaceToken: ${{ secrets.MARKETPLACE_TOKEN }}
          mavenVersion: '3.8.5'
